service: economist-news-quiz

custom:
  bucket: 'wine-bucket-serverless-dev-2'
  tableName: 'wine-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: serverless
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    BUCKET: ${self:custom.bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["WineDynamoDBTable", "Arn" ] }

functions:
  app:
    handler: server.handler
    events:
      - http: 'ANY {proxy+}'
  graphql:
    handler: graphql.graphqlHandler
    events:
      - http:
          path: 'graphql'
          method: any
          cors: true

resources:
  Resources:
    WineDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: productId
            AttributeType: S
        KeySchema:
          -
            AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 4
          WriteCapacityUnits: 4
        TableName: ${self:custom.tableName}